### ISSUE TITLE
[Question]  Is there a solution when pixel spacing occurs in a ListView?

### ISSUE THREAD

**Issue by DukeJeon** [irondash/pixel_snap#18]
Below is an example of my code.
Thank you for your hard work

```
ListView.builder(
      controller: _controller,
      scrollDirection: widget.scrollAxis,
      reverse: widget.reverse,
      padding: EdgeInsets.zero,
      physics: const NeverScrollableScrollPhysics(),
      itemBuilder: (_, i) => widget.child
    );
```

**Comment by knopp** [comment]
Basically pixel snapping works if all your widgets are pixel snapped. That means the widgets around `ListView` must be pixel snapped, and each of the list view items must be pixel snapped. Also you will need to use `PixelSnapScrollController` for the scroll controller, as it ensures that the scroll position is pixel snapped.

If you are using foreign widgets that size themselves and that you have no control over, you can wrap them in `PixelSnapSize` widget.

If you provide a runnable example that you have problem getting pixel snapped, I can take a look and try to fix it.

**Comment by DukeJeon** [comment]
The issue occurred in places where pixelsnap wasn't necessary, and it has been resolved.
Thank you for your answer.
