### ISSUE TITLE
Feature request: ListView

### ISSUE THREAD

**Issue by hgraceb** [irondash/pixel_snap#4]
## Feature request

Thank you for your amazing work. I'm having a problem with ListView, as shown in the following code and images. When I use `import 'package:flutter/material.dart';`, there seems to be a spacing between the images in some window sizes.

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Tests',
      home: const MyHomePage(),
      debugShowCheckedModeBanner: false,
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        dragDevices: PointerDeviceKind.values.toSet(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: ListView(
        children: List.generate(10, (index) {
          return const Image(
            image: NetworkImage('https://placehold.jp/fff/ccc/3333x317.png'),
          );
        }),
      ),
    );
  }
}

```

![Snipaste_2022-12-15_12-31-41](https://user-images.githubusercontent.com/38378650/207774871-59692c7a-9389-4ae1-b2f6-93fb43dc9245.jpg)

When I try to use `import 'package:pixel_snap/material.dart';`, the behavior changes to always having one pixel between images at some window sizes.

![Snipaste_2022-12-15_12-34-49](https://user-images.githubusercontent.com/38378650/207774909-59cd80b9-e5e4-4a58-957c-9b6e09a415ad.jpg)

Although this looks slightly better, it's still not "pixel-perfect". Could you please provide support for ListView, or give me any other suggestions to try?

If you think this is not a feature of the current plugin and that this is a problem with Flutter itself, I will close this feature request. Again, thank you for your work.

## Environments

- Flutter version: 3.3.3
- Windows scale: 125%
- Windows version: 21H2
- Test application size: 1584 x 892 px (Default)

**Comment by knopp** [comment]
The problem here is actually that the image itself is not pixel-snapped and to pixel-snap it, 0.0.1 wraps it in another widget. But that leaves some space around.

Can you try 0.0.2 and let me know if it works better?

**Comment by hgraceb** [comment]
Thank you, it's working perfectly now. I need to eat my words and apologize to `ListView`. However, I do have two more questions:

1. How should I replace the widgets used inside of a third-party plugin with pixel-snapped?

2. Do you have any plans to add a `RenderFittedBoxPixelSnap` or other widgets, as the current use of `FittedBox` can have similar issues as when using `Image`.

**Comment by hgraceb** [comment]
> The problem here is actually that the image itself is not pixel-snapped and to pixel-snap it, 0.0.1 wraps it in another widget. But that leaves some space around.
> 
> Can you try 0.0.2 and let me know if it works better?

Thank you, it's working perfectly now. I need to eat my words and apologize to `ListView`. However, I do have two more questions:

1. How should I replace the widgets used inside of a third-party plugin with pixel-snapped?

2. Do you have any plans to add a `RenderFittedBoxPixelSnap` or other widgets, as the current use of `FittedBox` can have similar issues as when using `Image`.

**Comment by knopp** [comment]
I added a forked version of `FittedBox` to 0.0.3, which itself should be pixel aligned (so it doesn't break parent layout pixel alignment), but I don't think it's always possible to have pixel aligned child, especially when it uses a scale transform. If you have example of FittedBox misbehaving you can provide one and I'll see if I can improve on it. But it general using `FittedBox` for part of app that needs to be pixel aligned is probably bad idea.

As for third-party packages, it really depends. There is no silver bullet here I'm afraid. If the widget lets you specify size, border, decoration, child, etc. you can `.pixelSnap()` those. If not but the widget is fully constrained by your layout then it may not render pixel snapped, but it shouldn't break your layout.

If the widget is not constrained and it sizes itself, you can wrap it with `PixelSnapSize`. It will not magically make the widget pixel-snapped, but will add enough space around it so that it doesn't break the rest of your layout.

**Comment by hgraceb** [comment]
Thank you very much. I did encounter some issues when using `FittedBox`. There are gaps appearing when adjusting the window size. The example code and effect are as follows:

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

import 'package:pixel_snap/material.dart' as ps;

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const MyHomePage(),
      debugShowCheckedModeBanner: false,
      scrollBehavior: const MaterialScrollBehavior().copyWith(
        dragDevices: PointerDeviceKind.values.toSet(),
      ),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: ListView(
        children: [
          Image(
            image: const NetworkImage(
              'https://user-images.githubusercontent.com/38378650/208236301-4db428e5-78b1-498a-b726-a5011987098c.png',
            ),
            frameBuilder: (context, child, frame, wasSynchronouslyLoaded) {
              if (wasSynchronouslyLoaded || frame != null) {
                return ps.FittedBox(child: child);
              }
              return child;
            },
          ),
          Image(
            image: const NetworkImage(
              'https://user-images.githubusercontent.com/38378650/208236302-7e8f1ac2-b1b8-41f9-aa68-5a0fa88c22a3.png',
            ),
            frameBuilder: (context, child, frame, wasSynchronouslyLoaded) {
              if (wasSynchronouslyLoaded || frame != null) {
                return ps.FittedBox(child: child);
              }
              return child;
            },
          ),
        ],
      ),
    );
  }
}
```

<img width="553" alt="Snipaste_2022-12-17_18-12-24" src="https://user-images.githubusercontent.com/38378650/208237163-61c789e9-97ac-496d-aa86-ad1fce791bfa.png">

I've found that the issue is caused by this code in the `pixel_snap.dart` file. Is it possible to change the `ceil` mode to use the default `snap` mode instead? In my testing, `ceil` mode always performs worse than `snap` or `floor` mode.

```dart
Size result = Size(
  constrainWidth(width.pixelSnap(PixelSnapMode.snap)),
  constrainHeight(
    height.pixelSnap(PixelSnapMode.ceil),
  ),
);
```

**Comment by hgraceb** [comment]
I implemented my `snap` mode `FittedBox` widget, which has additional `scale` handling and works perfectly. I'll close the issue for now.
